### ISSUE TITLE
Unable to install the library

### ISSUE THREAD

**Issue by ms8909** [ms8909/mltrons-auto-data-prep#24]
<img width="958" alt="Screenshot 2019-12-04 at 10 33 46 PM" src="https://user-images.githubusercontent.com/27916695/70202001-383c8180-16e6-11ea-9094-e5072938be33.png">

**Comment by tawabshakeel** [comment]
the issue is related Mac OS try this
https://stackoverflow.com/questions/25459386/mac-os-x-environmenterror-mysql-config-not-found
